### PR TITLE
Idioms

### PR DESCRIPTION
**Pull request by bananateg**
Please check this change with this is possible change language into app

### CODE REVIEW

**Comment by bananateg** [comment]
Change language at this moment for develop, using tab Contact Log

**Comment by kumpera** [comment]
Have you seen another PR with i18n merged?
And there's https://github.com/covidsafe/App-iOS/pull/135

**Comment by cheng-tan** [comment]
@bananateg is there any changes in this PR not covered by #135 and #148?

**Comment by kumpera** [comment]
Please follow the approach already merged in.

**Pull request closed without merging**
